# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29cacc000b464d5f9d55f64726c9ac9c09461c909633a7f3eec66ba94522919795f59e8c578e17fad5cb79056d1d20f2471edfe549cc4813ea2bc24c7fa1ce32

test:
  secret_key_base: cc23ae9d3072d1dd8f5f501101b6372c1faa751b4cc6098900c2cfb8e7e20f649a82f5ff8778416fe7ba7fae89798f6fbb065f8c4828e9bdffab52fd63c77f69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
